add_newline = true

format = """
╭─ $os$directory$character
╰─ 
"""
right_format = """
$git_branch$git_status$cmd_duration
"""

#left format, 1. os
[os]
disabled = false
style = "bg:white fg:black"
format = "[$symbol](bg:white fg:black)[ ](bg:blue fg:white)"

[os.symbols]
Arch = " "

#left format 2. directory
[directory]
truncation_length = 2
truncate_to_repo = true
style = "fg:cyan"
format = "[$path](bg:blue fg:white)[](bg:#1c1c1c fg:blue)"

[directory.substitutions]
"~" = " "
"~/.config/.dotfiles" = "repo"
".dotfiles" = "Dotfiles"

#left format 3. character
[character]
success_symbol = "[ ✔](bg:#1c1c1c fg:bold green)[](fg:#1c1c1c)"
error_symbol = "[ ✗](bg:#1c1c1c fg:bold red)[](fg:#1c1c1c)"

[git_branch]
symbol = " "
style = "bold green"
format = " [$branch]($style)"

[git_status]
style = "red"
untracked = ""

[cmd_duration]
min_time = 1000
format = "[$duration](fg:yellow)"
