paths:
  zshrc:
    my_config: zshrc.txt
    standard_config: ~/.zshrc

  hyprland:
    my_config: config.txt
    standard_config: ~/.config/hypr/hyprland.conf

  keyboardru:
    my_config: keyboardru
    standard_config: /usr/share/X11/xkb/symbols/ru

  python_path:
    script_utils: ~/.config/.dotfiles/system/system_installer/mytool/utils/
    cache_files: ~/.config/.dotfiles/system/system_installer/mytool/cache_files/
    configuration_yaml: ~/.config/.dotfiles/system/system_installer/mytool/config/configuration_yaml/
